// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use serde::{Deserialize, Serialize};
use validator::Validate;

/// Input for creating a new todo.
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreateTodoInput {
    #[validate(length(min = 1, max = 255))]
    pub title: String,

    pub description: Option<String>,

    pub completed: Option<bool>,

    #[serde(rename = "userId")]
    pub user_id: String,
}
