// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use serde::{Deserialize, Serialize};
use validator::Validate;
use super::user::UserStatus;

/// Input for creating a new user (server-generated fields omitted).
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreateUserInput {
    #[validate(email)]
    pub email: String,

    #[serde(rename = "displayName")]
    #[validate(length(min = 2, max = 100))]
    pub display_name: String,

    pub status: Option<UserStatus>,
}
