// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Public-facing todo (safe to return in API responses).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicTodo {
    pub id: String,
    pub title: String,
    pub description: Option<String>,
    pub completed: bool,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,
    #[serde(rename = "updatedAt")]
    pub updated_at: DateTime<Utc>,
}
