// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use super::user::UserStatus;

/// Public-facing user (safe to return in API responses).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicUser {
    pub id: String,
    pub email: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub status: UserStatus,
    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,
    #[serde(rename = "updatedAt")]
    pub updated_at: DateTime<Utc>,
}
