// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use validator::Validate;

/// Todo entity — maps to `todos` table.
#[derive(Debug, Clone, Serialize, Deserialize, Validate, sqlx::FromRow)]
pub struct Todo {
    pub id: String,

    #[validate(length(min = 1, max = 255))]
    pub title: String,

    pub description: Option<String>,

    pub completed: bool,

    #[serde(rename = "userId")]
    pub user_id: String,

    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,

    #[serde(rename = "updatedAt")]
    pub updated_at: DateTime<Utc>,
}
