// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use serde::{Deserialize, Serialize};
use validator::Validate;
use super::user::UserStatus;

/// Input for updating an existing user (all fields optional).
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct UpdateUserInput {
    #[validate(email)]
    pub email: Option<String>,

    #[serde(rename = "displayName")]
    #[validate(length(min = 2, max = 100))]
    pub display_name: Option<String>,

    pub status: Option<UserStatus>,
}
