// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use serde::{Deserialize, Serialize};
use validator::Validate;

/// Input for updating an existing todo (all fields optional).
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct UpdateTodoInput {
    #[validate(length(min = 1, max = 255))]
    pub title: Option<String>,

    pub description: Option<String>,

    pub completed: Option<bool>,
}
