// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use validator::Validate;

/// User account status.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, sqlx::Type)]
#[serde(rename_all = "snake_case")]
#[sqlx(type_name = "user_status", rename_all = "snake_case")]
pub enum UserStatus {
    Active,
    Suspended,
    Deleted,
}

/// User entity — maps to `users` table.
#[derive(Debug, Clone, Serialize, Deserialize, Validate, sqlx::FromRow)]
pub struct User {
    pub id: String,

    #[validate(email)]
    pub email: String,

    #[serde(rename = "displayName")]
    #[validate(length(min = 2, max = 100))]
    pub display_name: String,

    pub status: UserStatus,

    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,

    #[serde(rename = "updatedAt")]
    pub updated_at: DateTime<Utc>,
}
