import { describe, it, expect } from "@rstest/core";
import { DrizzleDatabaseAdapter, parseUnionValues } from "./index.js";
import type { SchemaTypeMap } from "@typokit/types";
import type { DatabaseState } from "@typokit/core";

describe("DrizzleDatabaseAdapter", () => {
  describe("parseUnionValues", () => {
    it("should parse string union types", () => {
      const values = parseUnionValues('"active" | "suspended" | "deleted"');
      expect(values).toEqual(["active", "suspended", "deleted"]);
    });

    it("should return null for non-union types", () => {
      expect(parseUnionValues("string")).toBeNull();
      expect(parseUnionValues("number")).toBeNull();
    });

    it("should return null for mixed unions", () => {
      expect(parseUnionValues('"a" | number')).toBeNull();
    });
  });

  describe("generate() - PostgreSQL", () => {
    const adapter = new DrizzleDatabaseAdapter({ dialect: "postgresql" });

    it("should generate Drizzle schema from User type", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "", generated: "uuid" } },
            email: { type: "string", optional: false, jsdoc: { format: "email", unique: "" } },
            displayName: { type: "string", optional: false, jsdoc: { maxLength: "100" } },
            status: {
              type: '"active" | "suspended" | "deleted"',
              optional: false,
              jsdoc: { default: "active" },
            },
            createdAt: { type: "Date", optional: false, jsdoc: { generated: "now" } },
            updatedAt: { type: "Date", optional: false, jsdoc: { onUpdate: "now" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);

      const output = outputs[0];
      expect(output.filePath).toBe("drizzle/users.ts");
      expect(output.overwrite).toBe(true);

      const content = output.content;

      // Header
      expect(content).toContain("// AUTO-GENERATED by @typokit/db-drizzle");

      // Imports
      expect(content).toContain('from "drizzle-orm/pg-core"');
      expect(content).toContain("pgTable");
      expect(content).toContain("pgEnum");
      expect(content).toContain("uuid");
      expect(content).toContain("varchar");
      expect(content).toContain("timestamp");

      // Enum
      expect(content).toContain("userStatusEnum");
      expect(content).toContain('pgEnum("user_status"');
      expect(content).toContain('"active", "suspended", "deleted"');

      // Table
      expect(content).toContain('pgTable("users"');

      // Columns
      expect(content).toContain('uuid("id")');
      expect(content).toContain(".defaultRandom()");
      expect(content).toContain(".primaryKey()");

      expect(content).toContain('varchar("email", { length: 255 })');
      expect(content).toContain(".unique()");

      expect(content).toContain('varchar("display_name", { length: 100 })');

      expect(content).toContain('userStatusEnum("status")');
      expect(content).toContain('.default("active")');

      expect(content).toContain('timestamp("created_at")');
      expect(content).toContain(".defaultNow()");

      expect(content).toContain('timestamp("updated_at")');
    });

    it("should handle all supported column types", () => {
      const types: SchemaTypeMap = {
        Product: {
          name: "Product",
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "", generated: "uuid" } },
            name: { type: "string", optional: false },
            price: { type: "number", optional: false },
            stock: { type: "bigint", optional: false },
            active: { type: "boolean", optional: false },
            metadata: { type: "Record<string, unknown>", optional: true },
            description: { type: "string", optional: true },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);
      const content = outputs[0].content;

      expect(content).toContain('uuid("id")');
      expect(content).toContain('text("name")');
      expect(content).toContain('integer("price")');
      expect(content).toContain('bigint("stock", { mode: "number" })');
      expect(content).toContain('boolean("active")');
      expect(content).toContain('jsonb("metadata")');
      expect(content).toContain('text("description")');

      // Required fields have .notNull()
      expect(content).toMatch(/text\("name"\)\.notNull\(\)/);
      // Optional fields do NOT have .notNull()
      expect(content).not.toMatch(/jsonb\("metadata"\)\.notNull\(\)/);
    });

    it("should use @table JSDoc tag for table name", () => {
      const types: SchemaTypeMap = {
        UserAccount: {
          name: "UserAccount",
          jsdoc: { table: "custom_accounts" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain('pgTable("custom_accounts"');
      expect(outputs[0].filePath).toBe("drizzle/custom_accounts.ts");
    });

    it("should pluralize table names from type names", () => {
      const types: SchemaTypeMap = {
        Category: {
          name: "Category",
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain('pgTable("categories"');
    });

    it("should generate enum for string union types", () => {
      const types: SchemaTypeMap = {
        Order: {
          name: "Order",
          properties: {
            status: {
              type: '"pending" | "shipped" | "delivered"',
              optional: false,
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      const content = outputs[0].content;
      expect(content).toContain("pgEnum");
      expect(content).toContain('orderStatusEnum');
      expect(content).toContain('"pending", "shipped", "delivered"');
    });

    it("should handle @default with numeric values", () => {
      const types: SchemaTypeMap = {
        Config: {
          name: "Config",
          properties: {
            retryCount: { type: "number", optional: false, jsdoc: { default: "3" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain(".default(3)");
    });
  });

  describe("generate() - SQLite", () => {
    const adapter = new DrizzleDatabaseAdapter({ dialect: "sqlite" });

    it("should generate SQLite schema", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
            name: { type: "string", optional: false },
            age: { type: "number", optional: false },
            active: { type: "boolean", optional: false },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);
      const content = outputs[0].content;

      expect(content).toContain('from "drizzle-orm/sqlite-core"');
      expect(content).toContain("sqliteTable");
      expect(content).toContain('text("id")');
      expect(content).toContain('text("name")');
      expect(content).toContain('integer("age")');
      expect(content).toContain('integer("active", { mode: "boolean" })');
    });
  });

  describe("diff()", () => {
    const adapter = new DrizzleDatabaseAdapter({ dialect: "postgresql" });

    it("should detect new tables", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = { tables: {} };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "add", entity: "users" });
      expect(draft.destructive).toBe(false);
    });

    it("should detect new columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            email: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("add");
      expect(draft.changes[0].field).toBe("email");
    });

    it("should detect removed columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
              old_col: { type: "text", nullable: true },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "remove", entity: "users", field: "old_col" });
      expect(draft.destructive).toBe(true);
    });

    it("should detect removed tables", () => {
      const types: SchemaTypeMap = {};
      const state: DatabaseState = {
        tables: {
          old_table: { columns: { id: { type: "text", nullable: false } } },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "remove", entity: "old_table" });
      expect(draft.destructive).toBe(true);
      expect(draft.sql).toContain("DROP TABLE");
    });

    it("should detect nullable changes", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            email: { type: "string", optional: true },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              email: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("modify");
    });

    it("should generate migration SQL", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            newField: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.sql).toContain('ALTER TABLE "users" ADD COLUMN "new_field" TEXT;');
      expect(draft.name).toMatch(/^\d{14}_schema_update$/);
    });
  });

  describe("constructor options", () => {
    it("should use custom output directory", () => {
      const adapter = new DrizzleDatabaseAdapter({ outputDir: "db/schema" });
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: { id: { type: "string", optional: false } },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].filePath).toContain("db/schema/");
    });

    it("should default to postgresql dialect", () => {
      const adapter = new DrizzleDatabaseAdapter();
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: { id: { type: "string", optional: false } },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("drizzle-orm/pg-core");
    });
  });
});
