import { describe, it, expect } from "@rstest/core";
import { KyselyDatabaseAdapter, parseUnionValues } from "./index.js";
import type { SchemaTypeMap } from "@typokit/types";
import type { DatabaseState } from "@typokit/core";

describe("KyselyDatabaseAdapter", () => {
  describe("parseUnionValues", () => {
    it("should parse string union types", () => {
      const values = parseUnionValues('"active" | "suspended" | "deleted"');
      expect(values).toEqual(["active", "suspended", "deleted"]);
    });

    it("should return null for non-union types", () => {
      expect(parseUnionValues("string")).toBeNull();
      expect(parseUnionValues("number")).toBeNull();
    });

    it("should return null for mixed unions", () => {
      expect(parseUnionValues('"a" | number')).toBeNull();
    });
  });

  describe("generate() - PostgreSQL", () => {
    const adapter = new KyselyDatabaseAdapter({ dialect: "postgresql" });

    it("should generate Kysely types from User type", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: {
              type: "string",
              optional: false,
              jsdoc: { id: "", generated: "uuid" },
            },
            email: {
              type: "string",
              optional: false,
              jsdoc: { format: "email", unique: "" },
            },
            displayName: {
              type: "string",
              optional: false,
              jsdoc: { maxLength: "100" },
            },
            status: {
              type: '"active" | "suspended" | "deleted"',
              optional: false,
              jsdoc: { default: "active" },
            },
            createdAt: {
              type: "Date",
              optional: false,
              jsdoc: { generated: "now" },
            },
            updatedAt: {
              type: "Date",
              optional: false,
              jsdoc: { onUpdate: "now" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);

      const output = outputs[0];
      expect(output.filePath).toBe("kysely/database.ts");
      expect(output.overwrite).toBe(true);

      const content = output.content;

      // Header
      expect(content).toContain("// AUTO-GENERATED by @typokit/db-kysely");

      // Generated import
      expect(content).toContain('import type { Generated } from "kysely"');

      // Table interface
      expect(content).toContain("export interface UserTable");

      // Columns — id is Generated<string> (auto-generated uuid)
      expect(content).toContain("id: Generated<string>");

      // email is plain string
      expect(content).toContain("email: string;");

      // displayName → display_name is plain string
      expect(content).toContain("display_name: string;");

      // status is Generated<union> (has default)
      expect(content).toContain(
        'status: Generated<"active" | "suspended" | "deleted">',
      );

      // createdAt → created_at is Generated<Date>
      expect(content).toContain("created_at: Generated<Date>");

      // updatedAt → updated_at is plain Date (onUpdate is not a generation)
      expect(content).toContain("updated_at: Date;");

      // Database interface
      expect(content).toContain("export interface Database");
      expect(content).toContain("users: UserTable;");
    });

    it("should handle all supported column types", () => {
      const types: SchemaTypeMap = {
        Product: {
          name: "Product",
          properties: {
            id: {
              type: "string",
              optional: false,
              jsdoc: { id: "", generated: "uuid" },
            },
            name: { type: "string", optional: false },
            price: { type: "number", optional: false },
            stock: { type: "bigint", optional: false },
            active: { type: "boolean", optional: false },
            metadata: { type: "Record<string, unknown>", optional: true },
            description: { type: "string", optional: true },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);
      const content = outputs[0].content;

      expect(content).toContain("id: Generated<string>");
      expect(content).toContain("name: string;");
      expect(content).toContain("price: number;");
      expect(content).toContain("stock: number;");
      expect(content).toContain("active: boolean;");
      expect(content).toContain("metadata: unknown | null;");
      expect(content).toContain("description: string | null;");
    });

    it("should use @table JSDoc tag for table name", () => {
      const types: SchemaTypeMap = {
        UserAccount: {
          name: "UserAccount",
          jsdoc: { table: "custom_accounts" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain(
        "custom_accounts: UserAccountTable;",
      );
    });

    it("should pluralize table names from type names", () => {
      const types: SchemaTypeMap = {
        Category: {
          name: "Category",
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("categories: CategoryTable;");
    });

    it("should handle string union types in PostgreSQL", () => {
      const types: SchemaTypeMap = {
        Order: {
          name: "Order",
          properties: {
            status: {
              type: '"pending" | "shipped" | "delivered"',
              optional: false,
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      const content = outputs[0].content;
      expect(content).toContain('"pending" | "shipped" | "delivered"');
    });

    it("should handle @default with Generated wrapper", () => {
      const types: SchemaTypeMap = {
        Config: {
          name: "Config",
          properties: {
            retryCount: {
              type: "number",
              optional: false,
              jsdoc: { default: "3" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("retry_count: Generated<number>");
    });
  });

  describe("generate() - SQLite", () => {
    const adapter = new KyselyDatabaseAdapter({ dialect: "sqlite" });

    it("should generate SQLite Kysely types", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
            name: { type: "string", optional: false },
            age: { type: "number", optional: false },
            active: { type: "boolean", optional: false },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);
      const content = outputs[0].content;

      // SQLite maps boolean → number, Date → string
      expect(content).toContain("id: string;");
      expect(content).toContain("name: string;");
      expect(content).toContain("age: number;");
      expect(content).toContain("active: number;");
    });

    it("should map Date to string in SQLite", () => {
      const types: SchemaTypeMap = {
        Event: {
          name: "Event",
          properties: {
            createdAt: {
              type: "Date",
              optional: false,
              jsdoc: { generated: "now" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("created_at: Generated<string>");
    });
  });

  describe("diff()", () => {
    const adapter = new KyselyDatabaseAdapter({ dialect: "postgresql" });

    it("should detect new tables", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = { tables: {} };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "add", entity: "users" });
      expect(draft.destructive).toBe(false);
    });

    it("should detect new columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            email: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("add");
      expect(draft.changes[0].field).toBe("email");
    });

    it("should detect removed columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
              old_col: { type: "text", nullable: true },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({
        type: "remove",
        entity: "users",
        field: "old_col",
      });
      expect(draft.destructive).toBe(true);
    });

    it("should detect removed tables", () => {
      const types: SchemaTypeMap = {};
      const state: DatabaseState = {
        tables: {
          old_table: { columns: { id: { type: "text", nullable: false } } },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "remove", entity: "old_table" });
      expect(draft.destructive).toBe(true);
      expect(draft.sql).toContain("DROP TABLE");
    });

    it("should detect nullable changes", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            email: { type: "string", optional: true },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              email: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("modify");
    });

    it("should generate migration SQL", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            newField: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.sql).toContain(
        'ALTER TABLE "users" ADD COLUMN "new_field" TEXT;',
      );
      expect(draft.name).toMatch(/^\d{14}_schema_update$/);
    });
  });

  describe("constructor options", () => {
    it("should use custom output directory", () => {
      const adapter = new KyselyDatabaseAdapter({ outputDir: "db/types" });
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: { id: { type: "string", optional: false } },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].filePath).toContain("db/types/");
    });

    it("should default to postgresql dialect", () => {
      const adapter = new KyselyDatabaseAdapter();
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: {
            active: { type: "boolean", optional: false },
          },
        },
      };

      const outputs = adapter.generate(types);
      // PostgreSQL maps boolean to boolean, not number
      expect(outputs[0].content).toContain("active: boolean;");
    });
  });
});
