// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

pub mod repository;

use sqlx::postgres::PgPool;

/// Connect to PostgreSQL and return a connection pool.
pub async fn connect(database_url: &str) -> PgPool {
    PgPool::connect(database_url)
        .await
        .expect("Failed to connect to database")
}
