// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use chrono::Utc;
use sqlx::postgres::PgPool;
use uuid::Uuid;

use crate::models::{
    CreateTodoInput, CreateUserInput, Todo, UpdateTodoInput, UpdateUserInput, User, UserStatus,
};

// ─────────────────────────── Users ───────────────────────────────────────────

pub async fn find_all_users(pool: &PgPool, page: u32, page_size: u32) -> sqlx::Result<Vec<User>> {
    let offset = ((page.saturating_sub(1)) * page_size) as i64;
    let limit = page_size as i64;

    sqlx::query_as::<_, User>(
        "SELECT id, email, display_name, status, created_at, updated_at \
         FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2",
    )
    .bind(limit)
    .bind(offset)
    .fetch_all(pool)
    .await
}

pub async fn count_users(pool: &PgPool) -> sqlx::Result<i64> {
    let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM users")
        .fetch_one(pool)
        .await?;
    Ok(row.0)
}

pub async fn find_user_by_id(pool: &PgPool, id: &str) -> sqlx::Result<Option<User>> {
    sqlx::query_as::<_, User>(
        "SELECT id, email, display_name, status, created_at, updated_at \
         FROM users WHERE id = $1",
    )
    .bind(id)
    .fetch_optional(pool)
    .await
}

pub async fn find_user_by_email(pool: &PgPool, email: &str) -> sqlx::Result<Option<User>> {
    sqlx::query_as::<_, User>(
        "SELECT id, email, display_name, status, created_at, updated_at \
         FROM users WHERE email = $1",
    )
    .bind(email)
    .fetch_optional(pool)
    .await
}

pub async fn create_user(pool: &PgPool, input: &CreateUserInput) -> sqlx::Result<User> {
    let id = Uuid::new_v4().to_string();
    let now = Utc::now();
    let status = input.status.clone().unwrap_or(UserStatus::Active);

    sqlx::query_as::<_, User>(
        "INSERT INTO users (id, email, display_name, status, created_at, updated_at) \
         VALUES ($1, $2, $3, $4, $5, $6) RETURNING *",
    )
    .bind(&id)
    .bind(&input.email)
    .bind(&input.display_name)
    .bind(&status)
    .bind(now)
    .bind(now)
    .fetch_one(pool)
    .await
}

pub async fn update_user(
    pool: &PgPool,
    id: &str,
    input: &UpdateUserInput,
) -> sqlx::Result<Option<User>> {
    let existing = find_user_by_id(pool, id).await?;
    let Some(existing) = existing else {
        return Ok(None);
    };

    let email = input.email.as_deref().unwrap_or(&existing.email);
    let display_name = input
        .display_name
        .as_deref()
        .unwrap_or(&existing.display_name);
    let status = input.status.as_ref().unwrap_or(&existing.status);
    let now = Utc::now();

    sqlx::query_as::<_, User>(
        "UPDATE users SET email = $2, display_name = $3, status = $4, updated_at = $5 \
         WHERE id = $1 RETURNING *",
    )
    .bind(id)
    .bind(email)
    .bind(display_name)
    .bind(status)
    .bind(now)
    .fetch_optional(pool)
    .await
}

pub async fn delete_user(pool: &PgPool, id: &str) -> sqlx::Result<Option<User>> {
    sqlx::query_as::<_, User>("DELETE FROM users WHERE id = $1 RETURNING *")
        .bind(id)
        .fetch_optional(pool)
        .await
}

// ─────────────────────────── Todos ───────────────────────────────────────────

pub async fn find_all_todos(pool: &PgPool, page: u32, page_size: u32) -> sqlx::Result<Vec<Todo>> {
    let offset = ((page.saturating_sub(1)) * page_size) as i64;
    let limit = page_size as i64;

    sqlx::query_as::<_, Todo>(
        "SELECT id, title, description, completed, user_id, created_at, updated_at \
         FROM todos ORDER BY created_at DESC LIMIT $1 OFFSET $2",
    )
    .bind(limit)
    .bind(offset)
    .fetch_all(pool)
    .await
}

pub async fn find_todos_filtered(
    pool: &PgPool,
    page: u32,
    page_size: u32,
    user_id: Option<&str>,
    completed: Option<bool>,
) -> sqlx::Result<Vec<Todo>> {
    let offset = ((page.saturating_sub(1)) * page_size) as i64;
    let limit = page_size as i64;

    sqlx::query_as::<_, Todo>(
        "SELECT id, title, description, completed, user_id, created_at, updated_at \
         FROM todos \
         WHERE ($3::text IS NULL OR user_id = $3) \
         AND ($4::boolean IS NULL OR completed = $4) \
         ORDER BY created_at DESC LIMIT $1 OFFSET $2",
    )
    .bind(limit)
    .bind(offset)
    .bind(user_id)
    .bind(completed)
    .fetch_all(pool)
    .await
}

pub async fn count_todos(
    pool: &PgPool,
    user_id: Option<&str>,
    completed: Option<bool>,
) -> sqlx::Result<i64> {
    let row: (i64,) = sqlx::query_as(
        "SELECT COUNT(*) FROM todos \
         WHERE ($1::text IS NULL OR user_id = $1) \
         AND ($2::boolean IS NULL OR completed = $2)",
    )
    .bind(user_id)
    .bind(completed)
    .fetch_one(pool)
    .await?;
    Ok(row.0)
}

pub async fn find_todo_by_id(pool: &PgPool, id: &str) -> sqlx::Result<Option<Todo>> {
    sqlx::query_as::<_, Todo>(
        "SELECT id, title, description, completed, user_id, created_at, updated_at \
         FROM todos WHERE id = $1",
    )
    .bind(id)
    .fetch_optional(pool)
    .await
}

pub async fn create_todo(pool: &PgPool, input: &CreateTodoInput) -> sqlx::Result<Todo> {
    let id = Uuid::new_v4().to_string();
    let now = Utc::now();
    let completed = input.completed.unwrap_or(false);

    sqlx::query_as::<_, Todo>(
        "INSERT INTO todos (id, title, description, completed, user_id, created_at, updated_at) \
         VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *",
    )
    .bind(&id)
    .bind(&input.title)
    .bind(&input.description)
    .bind(completed)
    .bind(&input.user_id)
    .bind(now)
    .bind(now)
    .fetch_one(pool)
    .await
}

pub async fn update_todo(
    pool: &PgPool,
    id: &str,
    input: &UpdateTodoInput,
) -> sqlx::Result<Option<Todo>> {
    let existing = find_todo_by_id(pool, id).await?;
    let Some(existing) = existing else {
        return Ok(None);
    };

    let title = input.title.as_deref().unwrap_or(&existing.title);
    let description = if input.description.is_some() {
        input.description.as_deref()
    } else {
        existing.description.as_deref()
    };
    let completed = input.completed.unwrap_or(existing.completed);
    let now = Utc::now();

    sqlx::query_as::<_, Todo>(
        "UPDATE todos SET title = $2, description = $3, completed = $4, updated_at = $5 \
         WHERE id = $1 RETURNING *",
    )
    .bind(id)
    .bind(title)
    .bind(description)
    .bind(completed)
    .bind(now)
    .fetch_optional(pool)
    .await
}

pub async fn delete_todo(pool: &PgPool, id: &str) -> sqlx::Result<Option<Todo>> {
    sqlx::query_as::<_, Todo>("DELETE FROM todos WHERE id = $1 RETURNING *")
        .bind(id)
        .fetch_optional(pool)
        .await
}
