// DO NOT EDIT — regenerated on schema change
// Generated by @typokit/testing contract-generator

import { describe, it, expect } from "@rstest/core";
import { createTestClient } from "@typokit/testing";
import type { TestClient } from "@typokit/testing";
import { createTestTodoApp, resetStore } from "../test-app.js";

// Shared client lifecycle
let client: TestClient;
let appInstance: ReturnType<typeof createTestTodoApp>;

async function setup(): Promise<void> {
  appInstance = createTestTodoApp();
  client = await createTestClient(appInstance);
  resetStore();
}

async function teardown(): Promise<void> {
  await client.close();
}

/** Helper: create a seed user and return its ID */
async function seedUser(): Promise<string> {
  const res = await client.post("/users", {
    body: { email: `seed-${Date.now()}@example.com`, displayName: "Seed User" },
  });
  return (res.body as { id: string }).id;
}

describe("Todos Contract Tests", () => {
  describe("GET /todos", () => {
    it("responds with 200", async () => {
      await setup();
      try {
        const res = await client.get("/todos");
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });
  });

  describe("POST /todos", () => {
    it("accepts valid CreateTodoInput", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const res = await client.post("/todos", {
          body: { title: "Test Todo", userId },
        });
        expect(res.status).toBe(201);
      } finally {
        await teardown();
      }
    });

    it("rejects missing required fields", async () => {
      await setup();
      try {
        const res = await client.post("/todos", { body: {} });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects missing 'title' field", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const res = await client.post("/todos", {
          body: { userId },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects missing 'userId' field", async () => {
      await setup();
      try {
        const res = await client.post("/todos", {
          body: { title: "Missing User" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });
  });

  describe("GET /todos/:id", () => {
    it("responds with 200 for existing todo", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const createRes = await client.post("/todos", {
          body: { title: "Get Test Todo", userId },
        });
        const todo = createRes.body as { id: string };
        const res = await client.get(`/todos/${todo.id}`);
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });

    it("responds with 404 for non-existent todo", async () => {
      await setup();
      try {
        const res = await client.get("/todos/nonexistent-id");
        expect(res.status).toBe(404);
      } finally {
        await teardown();
      }
    });
  });

  describe("PUT /todos/:id", () => {
    it("accepts valid UpdateTodoInput", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const createRes = await client.post("/todos", {
          body: { title: "Update Test Todo", userId },
        });
        const todo = createRes.body as { id: string };
        const res = await client.put(`/todos/${todo.id}`, {
          body: { title: "Updated Title", completed: true },
        });
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });

    it("rejects invalid completed format", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const createRes = await client.post("/todos", {
          body: { title: "Invalid Update Todo", userId },
        });
        const todo = createRes.body as { id: string };
        const res = await client.put(`/todos/${todo.id}`, {
          body: { completed: "not-a-boolean" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });
  });

  describe("DELETE /todos/:id", () => {
    it("responds with 204 for existing todo", async () => {
      await setup();
      try {
        const userId = await seedUser();
        const createRes = await client.post("/todos", {
          body: { title: "Delete Test Todo", userId },
        });
        const todo = createRes.body as { id: string };
        const res = await client.delete(`/todos/${todo.id}`);
        expect(res.status).toBe(204);
      } finally {
        await teardown();
      }
    });

    it("responds with 404 for non-existent todo", async () => {
      await setup();
      try {
        const res = await client.delete("/todos/nonexistent-id");
        expect(res.status).toBe(404);
      } finally {
        await teardown();
      }
    });
  });
});
