// DO NOT EDIT — regenerated on schema change
// Generated by @typokit/testing contract-generator

import { describe, it, expect } from "@rstest/core";
import { createTestClient } from "@typokit/testing";
import type { TestClient } from "@typokit/testing";
import { createTestTodoApp, resetStore } from "../test-app.js";

// Shared client lifecycle for all tests in this file
let client: TestClient;
let appInstance: ReturnType<typeof createTestTodoApp>;

async function setup(): Promise<void> {
  appInstance = createTestTodoApp();
  client = await createTestClient(appInstance);
}

async function teardown(): Promise<void> {
  await client.close();
}

describe("Users Contract Tests", () => {
  describe("GET /users", () => {
    it("responds with 200", async () => {
      await setup();
      try {
        const res = await client.get("/users");
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });
  });

  describe("POST /users", () => {
    it("accepts valid CreateUserInput", async () => {
      await setup();
      try {
        resetStore();
        const res = await client.post("/users", {
          body: {
            email: "test@example.com",
            displayName: "Test User",
          },
        });
        expect(res.status).toBe(201);
      } finally {
        await teardown();
      }
    });

    it("rejects missing required fields", async () => {
      await setup();
      try {
        const res = await client.post("/users", { body: {} });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects missing 'email' field", async () => {
      await setup();
      try {
        const res = await client.post("/users", {
          body: { displayName: "Test User" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects missing 'displayName' field", async () => {
      await setup();
      try {
        const res = await client.post("/users", {
          body: { email: "test@example.com" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects invalid email format", async () => {
      await setup();
      try {
        const res = await client.post("/users", {
          body: { email: "not-an-email", displayName: "Test User" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });
  });

  describe("GET /users/:id", () => {
    it("responds with 200 for existing user", async () => {
      await setup();
      try {
        resetStore();
        const createRes = await client.post("/users", {
          body: { email: "get-user@example.com", displayName: "Get Test" },
        });
        const user = createRes.body as { id: string };
        const res = await client.get(`/users/${user.id}`);
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });

    it("responds with 404 for non-existent user", async () => {
      await setup();
      try {
        const res = await client.get("/users/nonexistent-id");
        expect(res.status).toBe(404);
      } finally {
        await teardown();
      }
    });
  });

  describe("PUT /users/:id", () => {
    it("accepts valid UpdateUserInput", async () => {
      await setup();
      try {
        resetStore();
        const createRes = await client.post("/users", {
          body: { email: "put-user@example.com", displayName: "Put Test" },
        });
        const user = createRes.body as { id: string };
        const res = await client.put(`/users/${user.id}`, {
          body: { displayName: "Updated Name" },
        });
        expect(res.status).toBe(200);
      } finally {
        await teardown();
      }
    });

    it("rejects invalid email format", async () => {
      await setup();
      try {
        resetStore();
        const createRes = await client.post("/users", {
          body: { email: "put-invalid@example.com", displayName: "Put Invalid" },
        });
        const user = createRes.body as { id: string };
        const res = await client.put(`/users/${user.id}`, {
          body: { email: "not-an-email" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });

    it("rejects invalid status value", async () => {
      await setup();
      try {
        resetStore();
        const createRes = await client.post("/users", {
          body: { email: "put-status@example.com", displayName: "Put Status" },
        });
        const user = createRes.body as { id: string };
        const res = await client.put(`/users/${user.id}`, {
          body: { status: "__invalid_enum_value__" },
        });
        expect(res.status).toBe(400);
      } finally {
        await teardown();
      }
    });
  });

  describe("DELETE /users/:id", () => {
    it("responds with 204 for existing user", async () => {
      await setup();
      try {
        resetStore();
        const createRes = await client.post("/users", {
          body: { email: "del-user@example.com", displayName: "Delete Test" },
        });
        const user = createRes.body as { id: string };
        const res = await client.delete(`/users/${user.id}`);
        expect(res.status).toBe(204);
      } finally {
        await teardown();
      }
    });

    it("responds with 404 for non-existent user", async () => {
      await setup();
      try {
        const res = await client.delete("/users/nonexistent-id");
        expect(res.status).toBe(404);
      } finally {
        await teardown();
      }
    });
  });
});
