use std::collections::HashMap;
use crate::type_extractor::TypeMetadata;
use super::GeneratedOutput;

/// Generate Rust struct files from a SchemaTypeMap.
///
/// Produces one `.typokit/models/{entity}.rs` per type plus a
/// `.typokit/models/mod.rs` that re-exports all entity modules.
pub fn generate_structs(type_map: &HashMap<String, TypeMetadata>) -> Vec<GeneratedOutput> {
    let mut outputs = Vec::new();
    let mut module_names: Vec<String> = Vec::new();

    // Sort by name for deterministic output
    let mut sorted_types: Vec<(&String, &TypeMetadata)> = type_map.iter().collect();
    sorted_types.sort_by_key(|(name, _)| name.to_string());

    for (_name, metadata) in &sorted_types {
        let module_name = to_snake_case(&metadata.name);
        module_names.push(module_name.clone());

        let content = generate_struct_file(metadata);
        outputs.push(GeneratedOutput {
            path: format!(".typokit/models/{}.rs", module_name),
            content,
            overwrite: true,
        });
    }

    // Generate mod.rs that re-exports all entity modules
    let mod_content = generate_models_mod(&module_names);
    outputs.push(GeneratedOutput {
        path: ".typokit/models/mod.rs".to_string(),
        content: mod_content,
        overwrite: true,
    });

    outputs
}

/// Generate a single struct file for an entity
fn generate_struct_file(metadata: &TypeMetadata) -> String {
    let mut output = String::new();

    output.push_str("// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT\n");
    output.push_str("use serde::{Deserialize, Serialize};\n");

    let has_chrono = metadata.properties.values().any(|p| is_date_type(&p.type_str));
    if has_chrono {
        output.push_str("use chrono::{DateTime, Utc};\n");
    }

    output.push('\n');

    // Determine derives
    let has_table = metadata
        .jsdoc
        .as_ref()
        .map(|j| j.contains_key("table"))
        .unwrap_or(false);

    if has_table {
        output.push_str("#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]\n");
    } else {
        output.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    }

    output.push_str(&format!("pub struct {} {{\n", metadata.name));

    // Sort properties for deterministic output
    let mut sorted_props: Vec<(&String, &crate::type_extractor::PropertyMetadata)> =
        metadata.properties.iter().collect();
    sorted_props.sort_by_key(|(name, _)| name.to_string());

    for (prop_name, prop) in &sorted_props {
        let rust_type = ts_type_to_rust(&prop.type_str);
        let field_name = to_snake_case(prop_name);

        // Add serde rename if the field name differs from the original
        if field_name != **prop_name {
            output.push_str(&format!("    #[serde(rename = \"{}\")]\n", prop_name));
        }

        if prop.optional {
            output.push_str(&format!("    pub {}: Option<{}>,\n", field_name, rust_type));
        } else {
            output.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
        }
    }

    output.push_str("}\n");

    output
}

/// Generate the models/mod.rs file that re-exports all entity modules
fn generate_models_mod(module_names: &[String]) -> String {
    let mut output = String::new();
    output.push_str("// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT\n");

    for name in module_names {
        output.push_str(&format!("pub mod {};\n", name));
    }

    if !module_names.is_empty() {
        output.push('\n');
        for name in module_names {
            let struct_name = to_pascal_case(name);
            output.push_str(&format!("pub use {}::{};\n", name, struct_name));
        }
    }

    output
}

/// Map a TypeScript type string to a Rust type string
fn ts_type_to_rust(ts_type: &str) -> String {
    match ts_type {
        "string" => "String".to_string(),
        "number" => "f64".to_string(),
        "boolean" => "bool".to_string(),
        t if is_date_type(t) => "DateTime<Utc>".to_string(),
        "any" | "unknown" => "serde_json::Value".to_string(),
        "null" | "void" | "undefined" => "()".to_string(),

        // Array types: string[] → Vec<String>
        t if t.ends_with("[]") => {
            let inner = &t[..t.len() - 2];
            format!("Vec<{}>", ts_type_to_rust(inner))
        }
        // Array<T> → Vec<T>
        t if t.starts_with("Array<") && t.ends_with('>') => {
            let inner = &t[6..t.len() - 1];
            format!("Vec<{}>", ts_type_to_rust(inner))
        }
        // Record<K, V> → HashMap<K, V>
        t if t.starts_with("Record<") && t.ends_with('>') => {
            let inner = &t[7..t.len() - 1];
            if let Some((key, value)) = split_generic_args(inner) {
                format!(
                    "std::collections::HashMap<{}, {}>",
                    ts_type_to_rust(key.trim()),
                    ts_type_to_rust(value.trim())
                )
            } else {
                "std::collections::HashMap<String, serde_json::Value>".to_string()
            }
        }

        // Union literal types (e.g. "active" | "inactive") → String
        t if t.contains(" | ") => "String".to_string(),

        // Named type reference (e.g. other struct) — keep as-is
        t => t.to_string(),
    }
}

/// Check if a type string represents a Date type
fn is_date_type(ts_type: &str) -> bool {
    ts_type == "Date" || ts_type == "DateTime"
}

/// Split two generic type arguments separated by a comma at the top level
fn split_generic_args(s: &str) -> Option<(&str, &str)> {
    let mut depth = 0;
    for (i, c) in s.char_indices() {
        match c {
            '<' => depth += 1,
            '>' => depth -= 1,
            ',' if depth == 0 => {
                return Some((&s[..i], &s[i + 1..]));
            }
            _ => {}
        }
    }
    None
}

/// Convert a camelCase or PascalCase string to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert a snake_case string to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::type_extractor::{PropertyMetadata, TypeMetadata};

    fn make_type(name: &str, props: Vec<(&str, &str, bool)>) -> TypeMetadata {
        let mut properties = HashMap::new();
        for (pname, ptype, optional) in props {
            properties.insert(
                pname.to_string(),
                PropertyMetadata {
                    type_str: ptype.to_string(),
                    optional,
                    jsdoc: None,
                },
            );
        }
        TypeMetadata {
            name: name.to_string(),
            properties,
            jsdoc: None,
        }
    }

    fn make_table_type(name: &str, table_name: &str, props: Vec<(&str, &str, bool)>) -> TypeMetadata {
        let mut metadata = make_type(name, props);
        let mut jsdoc = HashMap::new();
        jsdoc.insert("table".to_string(), table_name.to_string());
        metadata.jsdoc = Some(jsdoc);
        metadata
    }

    #[test]
    fn test_ts_type_to_rust_primitives() {
        assert_eq!(ts_type_to_rust("string"), "String");
        assert_eq!(ts_type_to_rust("number"), "f64");
        assert_eq!(ts_type_to_rust("boolean"), "bool");
        assert_eq!(ts_type_to_rust("Date"), "DateTime<Utc>");
    }

    #[test]
    fn test_ts_type_to_rust_arrays() {
        assert_eq!(ts_type_to_rust("string[]"), "Vec<String>");
        assert_eq!(ts_type_to_rust("number[]"), "Vec<f64>");
        assert_eq!(ts_type_to_rust("Array<string>"), "Vec<String>");
    }

    #[test]
    fn test_ts_type_to_rust_record() {
        assert_eq!(
            ts_type_to_rust("Record<string, unknown>"),
            "std::collections::HashMap<String, serde_json::Value>"
        );
    }

    #[test]
    fn test_ts_type_to_rust_optional_maps_to_option() {
        // Optional is handled at struct level, not in ts_type_to_rust
        assert_eq!(ts_type_to_rust("string"), "String");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("createdAt"), "created_at");
        assert_eq!(to_snake_case("userId"), "user_id");
        assert_eq!(to_snake_case("User"), "user");
        assert_eq!(to_snake_case("HTMLParser"), "h_t_m_l_parser");
        assert_eq!(to_snake_case("id"), "id");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("user"), "User");
        assert_eq!(to_pascal_case("created_at"), "CreatedAt");
        assert_eq!(to_pascal_case("user_profile"), "UserProfile");
    }

    #[test]
    fn test_generate_simple_struct() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "User".to_string(),
            make_type("User", vec![
                ("id", "string", false),
                ("name", "string", false),
                ("age", "number", false),
                ("active", "boolean", false),
            ]),
        );

        let outputs = generate_structs(&type_map);

        // Should have 2 outputs: user.rs and mod.rs
        assert_eq!(outputs.len(), 2);

        let user_file = outputs.iter().find(|o| o.path.contains("user.rs")).unwrap();
        assert!(user_file.content.contains("pub struct User"));
        assert!(user_file.content.contains("pub id: String"));
        assert!(user_file.content.contains("pub name: String"));
        assert!(user_file.content.contains("pub age: f64"));
        assert!(user_file.content.contains("pub active: bool"));
        assert!(user_file.content.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));
        assert!(!user_file.content.contains("sqlx::FromRow"));
        assert!(user_file.overwrite);
    }

    #[test]
    fn test_generate_table_struct_has_sqlx_derive() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "User".to_string(),
            make_table_type("User", "users", vec![
                ("id", "string", false),
                ("name", "string", false),
            ]),
        );

        let outputs = generate_structs(&type_map);
        let user_file = outputs.iter().find(|o| o.path.contains("user.rs")).unwrap();
        assert!(user_file.content.contains("sqlx::FromRow"));
    }

    #[test]
    fn test_generate_optional_fields() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "Profile".to_string(),
            make_type("Profile", vec![
                ("bio", "string", true),
                ("age", "number", true),
                ("name", "string", false),
            ]),
        );

        let outputs = generate_structs(&type_map);
        let profile_file = outputs.iter().find(|o| o.path.contains("profile.rs")).unwrap();
        assert!(profile_file.content.contains("pub bio: Option<String>"));
        assert!(profile_file.content.contains("pub age: Option<f64>"));
        assert!(profile_file.content.contains("pub name: String"));
    }

    #[test]
    fn test_generate_date_fields() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "Event".to_string(),
            make_type("Event", vec![
                ("id", "string", false),
                ("createdAt", "Date", false),
                ("updatedAt", "Date", true),
            ]),
        );

        let outputs = generate_structs(&type_map);
        let event_file = outputs.iter().find(|o| o.path.contains("event.rs")).unwrap();
        assert!(event_file.content.contains("use chrono::{DateTime, Utc};"));
        assert!(event_file.content.contains("pub created_at: DateTime<Utc>"));
        assert!(event_file.content.contains("pub updated_at: Option<DateTime<Utc>>"));
    }

    #[test]
    fn test_generate_camel_case_fields_get_serde_rename() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "User".to_string(),
            make_type("User", vec![
                ("id", "string", false),
                ("createdAt", "Date", false),
            ]),
        );

        let outputs = generate_structs(&type_map);
        let user_file = outputs.iter().find(|o| o.path.contains("user.rs")).unwrap();
        // "id" stays "id", no rename needed
        assert!(!user_file.content.contains("#[serde(rename = \"id\")]"));
        // "createdAt" → "created_at" needs rename
        assert!(user_file.content.contains("#[serde(rename = \"createdAt\")]"));
    }

    #[test]
    fn test_generate_mod_rs() {
        let mut type_map = HashMap::new();
        type_map.insert("User".to_string(), make_type("User", vec![("id", "string", false)]));
        type_map.insert("Post".to_string(), make_type("Post", vec![("id", "string", false)]));

        let outputs = generate_structs(&type_map);
        let mod_file = outputs.iter().find(|o| o.path.ends_with("mod.rs")).unwrap();
        assert!(mod_file.content.contains("pub mod post;"));
        assert!(mod_file.content.contains("pub mod user;"));
        assert!(mod_file.content.contains("pub use post::Post;"));
        assert!(mod_file.content.contains("pub use user::User;"));
        assert!(mod_file.overwrite);
    }

    #[test]
    fn test_generate_file_paths() {
        let mut type_map = HashMap::new();
        type_map.insert(
            "UserProfile".to_string(),
            make_type("UserProfile", vec![("id", "string", false)]),
        );

        let outputs = generate_structs(&type_map);
        let struct_file = outputs.iter().find(|o| !o.path.ends_with("mod.rs")).unwrap();
        assert_eq!(struct_file.path, ".typokit/models/user_profile.rs");
    }

    #[test]
    fn test_all_outputs_have_overwrite_true() {
        let mut type_map = HashMap::new();
        type_map.insert("User".to_string(), make_type("User", vec![("id", "string", false)]));

        let outputs = generate_structs(&type_map);
        for output in &outputs {
            assert!(output.overwrite, "All generated model files should have overwrite: true");
        }
    }
}
