import { describe, it, expect } from "@rstest/core";
import { PrismaDatabaseAdapter, parseUnionValues } from "./index.js";
import type { SchemaTypeMap } from "@typokit/types";
import type { DatabaseState } from "@typokit/core";

describe("PrismaDatabaseAdapter", () => {
  describe("parseUnionValues", () => {
    it("should parse string union types", () => {
      const values = parseUnionValues('"active" | "suspended" | "deleted"');
      expect(values).toEqual(["active", "suspended", "deleted"]);
    });

    it("should return null for non-union types", () => {
      expect(parseUnionValues("string")).toBeNull();
      expect(parseUnionValues("number")).toBeNull();
    });

    it("should return null for mixed unions", () => {
      expect(parseUnionValues('"a" | number')).toBeNull();
    });
  });

  describe("generate() - PostgreSQL", () => {
    const adapter = new PrismaDatabaseAdapter({ provider: "postgresql" });

    it("should generate Prisma schema from User type", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: {
              type: "string",
              optional: false,
              jsdoc: { id: "", generated: "uuid" },
            },
            email: {
              type: "string",
              optional: false,
              jsdoc: { format: "email", unique: "" },
            },
            displayName: {
              type: "string",
              optional: false,
              jsdoc: { maxLength: "100" },
            },
            status: {
              type: '"active" | "suspended" | "deleted"',
              optional: false,
              jsdoc: { default: "active" },
            },
            createdAt: {
              type: "Date",
              optional: false,
              jsdoc: { generated: "now" },
            },
            updatedAt: {
              type: "Date",
              optional: false,
              jsdoc: { onUpdate: "now" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);

      const output = outputs[0];
      expect(output.filePath).toBe("prisma/schema.prisma");
      expect(output.overwrite).toBe(true);

      const content = output.content;

      // Header
      expect(content).toContain("// AUTO-GENERATED by @typokit/db-prisma");

      // Datasource
      expect(content).toContain('provider = "postgresql"');
      expect(content).toContain('url      = env("DATABASE_URL")');

      // Generator
      expect(content).toContain('provider = "prisma-client-js"');

      // Enum
      expect(content).toContain("enum UserStatus");
      expect(content).toContain("  active");
      expect(content).toContain("  suspended");
      expect(content).toContain("  deleted");

      // Model
      expect(content).toContain("model User");

      // Fields
      expect(content).toContain("id String @id @default(uuid())");
      expect(content).toContain("email String @unique");
      expect(content).toContain("displayName String");
      expect(content).toContain('@map("display_name")');
      expect(content).toContain("status UserStatus @default(active)");
      expect(content).toContain("createdAt DateTime @default(now())");
      expect(content).toContain('@map("created_at")');
      expect(content).toContain("updatedAt DateTime @updatedAt");
      expect(content).toContain('@map("updated_at")');

      // Table mapping
      expect(content).toContain('@@map("users")');
    });

    it("should handle all supported column types", () => {
      const types: SchemaTypeMap = {
        Product: {
          name: "Product",
          properties: {
            id: {
              type: "string",
              optional: false,
              jsdoc: { id: "", generated: "uuid" },
            },
            name: { type: "string", optional: false },
            price: { type: "number", optional: false },
            stock: { type: "bigint", optional: false },
            active: { type: "boolean", optional: false },
            metadata: { type: "Record<string, unknown>", optional: true },
            description: { type: "string", optional: true },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs).toHaveLength(1);
      const content = outputs[0].content;

      expect(content).toContain("id String @id @default(uuid())");
      expect(content).toContain("name String");
      expect(content).toContain("price Int");
      expect(content).toContain("stock BigInt");
      expect(content).toContain("active Boolean");
      expect(content).toContain("metadata Json?");
      expect(content).toContain("description String?");
    });

    it("should use @table JSDoc tag for table name", () => {
      const types: SchemaTypeMap = {
        UserAccount: {
          name: "UserAccount",
          jsdoc: { table: "custom_accounts" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain('@@map("custom_accounts")');
    });

    it("should generate enum for string union types", () => {
      const types: SchemaTypeMap = {
        Order: {
          name: "Order",
          properties: {
            status: {
              type: '"pending" | "shipped" | "delivered"',
              optional: false,
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      const content = outputs[0].content;
      expect(content).toContain("enum OrderStatus");
      expect(content).toContain("  pending");
      expect(content).toContain("  shipped");
      expect(content).toContain("  delivered");
      expect(content).toContain("status OrderStatus");
    });

    it("should handle @default with numeric values", () => {
      const types: SchemaTypeMap = {
        Config: {
          name: "Config",
          properties: {
            retryCount: {
              type: "number",
              optional: false,
              jsdoc: { default: "3" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("@default(3)");
    });

    it("should handle autoincrement", () => {
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: {
            id: {
              type: "number",
              optional: false,
              jsdoc: { id: "", generated: "autoincrement" },
            },
          },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain("@default(autoincrement())");
    });
  });

  describe("generate() - SQLite", () => {
    const adapter = new PrismaDatabaseAdapter({ provider: "sqlite" });

    it("should generate SQLite datasource", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false, jsdoc: { id: "" } },
            name: { type: "string", optional: false },
          },
        },
      };

      const outputs = adapter.generate(types);
      const content = outputs[0].content;

      expect(content).toContain('provider = "sqlite"');
      expect(content).toContain("model User");
    });
  });

  describe("diff()", () => {
    const adapter = new PrismaDatabaseAdapter({ provider: "postgresql" });

    it("should detect new tables", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = { tables: {} };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "add", entity: "users" });
      expect(draft.destructive).toBe(false);
    });

    it("should detect new columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            email: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("add");
      expect(draft.changes[0].field).toBe("email");
    });

    it("should detect removed columns", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
              old_col: { type: "text", nullable: true },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({
        type: "remove",
        entity: "users",
        field: "old_col",
      });
      expect(draft.destructive).toBe(true);
    });

    it("should detect removed tables", () => {
      const types: SchemaTypeMap = {};
      const state: DatabaseState = {
        tables: {
          old_table: { columns: { id: { type: "text", nullable: false } } },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0]).toEqual({ type: "remove", entity: "old_table" });
      expect(draft.destructive).toBe(true);
      expect(draft.sql).toContain("DROP TABLE");
    });

    it("should detect nullable changes", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            email: { type: "string", optional: true },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              email: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.changes).toHaveLength(1);
      expect(draft.changes[0].type).toBe("modify");
    });

    it("should generate migration SQL", () => {
      const types: SchemaTypeMap = {
        User: {
          name: "User",
          jsdoc: { table: "users" },
          properties: {
            id: { type: "string", optional: false },
            newField: { type: "string", optional: false },
          },
        },
      };
      const state: DatabaseState = {
        tables: {
          users: {
            columns: {
              id: { type: "text", nullable: false },
            },
          },
        },
      };

      const draft = adapter.diff(types, state);
      expect(draft.sql).toContain(
        'ALTER TABLE "users" ADD COLUMN "new_field" TEXT;',
      );
      expect(draft.name).toMatch(/^\d{14}_schema_update$/);
    });
  });

  describe("constructor options", () => {
    it("should use custom output directory", () => {
      const adapter = new PrismaDatabaseAdapter({ outputDir: "db/schema" });
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: { id: { type: "string", optional: false } },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].filePath).toContain("db/schema/");
    });

    it("should default to postgresql provider", () => {
      const adapter = new PrismaDatabaseAdapter();
      const types: SchemaTypeMap = {
        Item: {
          name: "Item",
          properties: { id: { type: "string", optional: false } },
        },
      };

      const outputs = adapter.generate(types);
      expect(outputs[0].content).toContain('provider = "postgresql"');
    });
  });
});
