use super::GeneratedOutput;

/// Generate middleware stub files.
///
/// Produces:
/// - `src/middleware/auth.rs` with an Axum middleware stub (overwrite: false)
/// - `src/middleware/mod.rs` with pub mod auth declaration (overwrite: true)
pub fn generate_middleware() -> Vec<GeneratedOutput> {
    vec![
        generate_auth_middleware(),
        generate_middleware_mod(),
    ]
}

/// Generate the `src/middleware/auth.rs` with an Axum middleware stub.
fn generate_auth_middleware() -> GeneratedOutput {
    let mut s = String::new();

    s.push_str("// AUTO-GENERATED by @typokit/transform-native\n");
    s.push_str("// This file will NOT be overwritten — edit freely.\n\n");

    s.push_str("use axum::{\n");
    s.push_str("    extract::Request,\n");
    s.push_str("    http::StatusCode,\n");
    s.push_str("    middleware::Next,\n");
    s.push_str("    response::Response,\n");
    s.push_str("};\n\n");

    s.push_str("/// Authentication middleware.\n");
    s.push_str("///\n");
    s.push_str("/// Validates the incoming request for authentication credentials.\n");
    s.push_str("/// Attach to routes via `axum::middleware::from_fn(auth)`.\n");
    s.push_str("pub async fn auth(\n");
    s.push_str("    request: Request,\n");
    s.push_str("    next: Next,\n");
    s.push_str(") -> Result<Response, StatusCode> {\n");
    s.push_str("    // TODO: Implement authentication logic\n");
    s.push_str("    // Example: Check for a valid Bearer token in the Authorization header\n");
    s.push_str("    //\n");
    s.push_str("    // let auth_header = request\n");
    s.push_str("    //     .headers()\n");
    s.push_str("    //     .get(\"Authorization\")\n");
    s.push_str("    //     .and_then(|v| v.to_str().ok());\n");
    s.push_str("    //\n");
    s.push_str("    // match auth_header {\n");
    s.push_str("    //     Some(token) if token.starts_with(\"Bearer \") => {\n");
    s.push_str("    //         // Validate the token here\n");
    s.push_str("    //         Ok(next.run(request).await)\n");
    s.push_str("    //     }\n");
    s.push_str("    //     _ => Err(StatusCode::UNAUTHORIZED),\n");
    s.push_str("    // }\n");
    s.push_str("\n");
    s.push_str("    Ok(next.run(request).await)\n");
    s.push_str("}\n");

    GeneratedOutput {
        path: "src/middleware/auth.rs".to_string(),
        content: s,
        overwrite: false,
    }
}

/// Generate the `src/middleware/mod.rs` with pub mod declarations.
fn generate_middleware_mod() -> GeneratedOutput {
    let mut output = String::new();
    output.push_str("// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT\n\n");
    output.push_str("pub mod auth;\n");

    GeneratedOutput {
        path: "src/middleware/mod.rs".to_string(),
        content: output,
        overwrite: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_middleware_produces_two_files() {
        let outputs = generate_middleware();
        assert_eq!(outputs.len(), 2);
    }

    #[test]
    fn test_auth_middleware_file_path() {
        let outputs = generate_middleware();
        let auth = outputs.iter().find(|o| o.path == "src/middleware/auth.rs").unwrap();
        assert!(!auth.overwrite);
    }

    #[test]
    fn test_auth_middleware_uses_from_fn_pattern() {
        let outputs = generate_middleware();
        let auth = outputs.iter().find(|o| o.path == "src/middleware/auth.rs").unwrap();
        assert!(auth.content.contains("pub async fn auth("));
        assert!(auth.content.contains("request: Request"));
        assert!(auth.content.contains("next: Next"));
        assert!(auth.content.contains("Result<Response, StatusCode>"));
    }

    #[test]
    fn test_auth_middleware_calls_next() {
        let outputs = generate_middleware();
        let auth = outputs.iter().find(|o| o.path == "src/middleware/auth.rs").unwrap();
        assert!(auth.content.contains("next.run(request).await"));
    }

    #[test]
    fn test_auth_middleware_imports() {
        let outputs = generate_middleware();
        let auth = outputs.iter().find(|o| o.path == "src/middleware/auth.rs").unwrap();
        assert!(auth.content.contains("use axum::"));
        assert!(auth.content.contains("extract::Request"));
        assert!(auth.content.contains("middleware::Next"));
        assert!(auth.content.contains("response::Response"));
        assert!(auth.content.contains("http::StatusCode"));
    }

    #[test]
    fn test_auth_middleware_no_overwrite() {
        let outputs = generate_middleware();
        let auth = outputs.iter().find(|o| o.path == "src/middleware/auth.rs").unwrap();
        assert!(!auth.overwrite);
        assert!(auth.content.contains("will NOT be overwritten"));
    }

    #[test]
    fn test_middleware_mod_file() {
        let outputs = generate_middleware();
        let mod_file = outputs.iter().find(|o| o.path == "src/middleware/mod.rs").unwrap();
        assert!(mod_file.overwrite);
        assert!(mod_file.content.contains("pub mod auth;"));
    }

    #[test]
    fn test_middleware_mod_overwrite_true() {
        let outputs = generate_middleware();
        let mod_file = outputs.iter().find(|o| o.path == "src/middleware/mod.rs").unwrap();
        assert!(mod_file.overwrite);
    }

    #[test]
    fn test_deterministic_output() {
        let outputs1 = generate_middleware();
        let outputs2 = generate_middleware();

        assert_eq!(outputs1.len(), outputs2.len());
        for (a, b) in outputs1.iter().zip(outputs2.iter()) {
            assert_eq!(a.path, b.path);
            assert_eq!(a.content, b.content);
            assert_eq!(a.overwrite, b.overwrite);
        }
    }
}
