use super::GeneratedOutput;

/// Generate the complete Rust project scaffold.
///
/// Produces:
/// - `Cargo.toml` — dependencies and package metadata (overwrite: true)
/// - `src/main.rs` — tokio entrypoint with dotenvy, tracing, db pool, axum::serve (overwrite: true)
/// - `src/lib.rs` — #[path] attributes bridging .typokit/ modules plus pub mod for user code (overwrite: true)
/// - `.typokit/app.rs` — AppState struct with PgPool (overwrite: true)
/// - `.typokit/error.rs` — AppError enum implementing IntoResponse (overwrite: true)
pub fn generate_project() -> Vec<GeneratedOutput> {
    vec![
        generate_cargo_toml(),
        generate_main_rs(),
        generate_lib_rs(),
        generate_app_rs(),
        generate_error_rs(),
    ]
}

// ─────────────────────────── Cargo.toml ──────────────────────────────────────

fn generate_cargo_toml() -> GeneratedOutput {
    let content = r#"# AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
validator = { version = "0.19", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
dotenvy = "0.15"
"#;

    GeneratedOutput {
        path: "Cargo.toml".to_string(),
        content: content.to_string(),
        overwrite: true,
    }
}

// ─────────────────────────── src/main.rs ─────────────────────────────────────

fn generate_main_rs() -> GeneratedOutput {
    let content = r#"// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use server::app::AppState;
use server::db;
use server::router::create_router;

#[tokio::main]
async fn main() {
    dotenvy::dotenv().ok();

    tracing_subscriber::fmt::init();

    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");

    let pool = db::connect(&database_url).await;

    let state = AppState { pool };
    let app = create_router().with_state(state);

    let port = std::env::var("PORT").unwrap_or_else(|_| "3000".to_string());
    let addr = format!("0.0.0.0:{}", port);

    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .unwrap_or_else(|_| panic!("Failed to bind to {}", addr));

    tracing::info!("Server listening on {}", addr);

    axum::serve(listener, app)
        .await
        .expect("Server error");
}
"#;

    GeneratedOutput {
        path: "src/main.rs".to_string(),
        content: content.to_string(),
        overwrite: true,
    }
}

// ─────────────────────────── src/lib.rs ──────────────────────────────────────

fn generate_lib_rs() -> GeneratedOutput {
    let content = r#"// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

#[path = "../.typokit/models/mod.rs"]
pub mod models;

#[path = "../.typokit/router.rs"]
pub mod router;

#[path = "../.typokit/db/mod.rs"]
pub mod db;

#[path = "../.typokit/app.rs"]
pub mod app;

#[path = "../.typokit/error.rs"]
pub mod error;

pub mod handlers;
pub mod services;
pub mod middleware;
"#;

    GeneratedOutput {
        path: "src/lib.rs".to_string(),
        content: content.to_string(),
        overwrite: true,
    }
}

// ─────────────────────────── .typokit/app.rs ─────────────────────────────────

fn generate_app_rs() -> GeneratedOutput {
    let content = r#"// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use sqlx::postgres::PgPool;

/// Shared application state passed to all route handlers.
#[derive(Clone)]
pub struct AppState {
    pub pool: PgPool,
}
"#;

    GeneratedOutput {
        path: ".typokit/app.rs".to_string(),
        content: content.to_string(),
        overwrite: true,
    }
}

// ─────────────────────────── .typokit/error.rs ───────────────────────────────

fn generate_error_rs() -> GeneratedOutput {
    let content = r#"// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use axum::{
    http::StatusCode,
    response::{IntoResponse, Response},
    Json,
};
use serde_json::json;

/// Application error type with HTTP status code mapping.
///
/// Handlers return `Result<T, AppError>` and Axum automatically
/// converts `AppError` into an HTTP response via `IntoResponse`.
#[derive(Debug)]
pub enum AppError {
    NotFound(String),
    BadRequest(String),
    Unauthorized(String),
    Forbidden(String),
    Conflict(String),
    Internal(String),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, message) = match self {
            AppError::NotFound(msg) => (StatusCode::NOT_FOUND, msg),
            AppError::BadRequest(msg) => (StatusCode::BAD_REQUEST, msg),
            AppError::Unauthorized(msg) => (StatusCode::UNAUTHORIZED, msg),
            AppError::Forbidden(msg) => (StatusCode::FORBIDDEN, msg),
            AppError::Conflict(msg) => (StatusCode::CONFLICT, msg),
            AppError::Internal(msg) => (StatusCode::INTERNAL_SERVER_ERROR, msg),
        };

        let body = Json(json!({
            "error": status.as_u16(),
            "message": message,
        }));

        (status, body).into_response()
    }
}

impl AppError {
    pub fn not_found(msg: impl Into<String>) -> Self {
        Self::NotFound(msg.into())
    }

    pub fn bad_request(msg: impl Into<String>) -> Self {
        Self::BadRequest(msg.into())
    }

    pub fn unauthorized(msg: impl Into<String>) -> Self {
        Self::Unauthorized(msg.into())
    }

    pub fn forbidden(msg: impl Into<String>) -> Self {
        Self::Forbidden(msg.into())
    }

    pub fn conflict(msg: impl Into<String>) -> Self {
        Self::Conflict(msg.into())
    }

    pub fn internal(msg: impl Into<String>) -> Self {
        Self::Internal(msg.into())
    }
}

impl std::fmt::Display for AppError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AppError::NotFound(msg) => write!(f, "Not Found: {}", msg),
            AppError::BadRequest(msg) => write!(f, "Bad Request: {}", msg),
            AppError::Unauthorized(msg) => write!(f, "Unauthorized: {}", msg),
            AppError::Forbidden(msg) => write!(f, "Forbidden: {}", msg),
            AppError::Conflict(msg) => write!(f, "Conflict: {}", msg),
            AppError::Internal(msg) => write!(f, "Internal Server Error: {}", msg),
        }
    }
}
"#;

    GeneratedOutput {
        path: ".typokit/error.rs".to_string(),
        content: content.to_string(),
        overwrite: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_project_produces_five_files() {
        let outputs = generate_project();
        assert_eq!(outputs.len(), 5);
    }

    // ─── Cargo.toml ─────────────────────────────────────────────────────

    #[test]
    fn test_cargo_toml_path_and_overwrite() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.overwrite);
    }

    #[test]
    fn test_cargo_toml_edition_2024() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("edition = \"2024\""));
    }

    #[test]
    fn test_cargo_toml_package_metadata() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("[package]"));
        assert!(cargo.content.contains("name = \"server\""));
        assert!(cargo.content.contains("version = \"0.1.0\""));
    }

    #[test]
    fn test_cargo_toml_axum_dependency() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("axum = \"0.8\""));
    }

    #[test]
    fn test_cargo_toml_tokio_full() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("tokio = { version = \"1\", features = [\"full\"] }"));
    }

    #[test]
    fn test_cargo_toml_serde_derive() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("serde = { version = \"1\", features = [\"derive\"] }"));
        assert!(cargo.content.contains("serde_json = \"1\""));
    }

    #[test]
    fn test_cargo_toml_validator() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("validator = { version = \"0.19\", features = [\"derive\"] }"));
    }

    #[test]
    fn test_cargo_toml_chrono_serde() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("chrono = { version = \"0.4\", features = [\"serde\"] }"));
    }

    #[test]
    fn test_cargo_toml_uuid() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("uuid = \"1\""));
    }

    #[test]
    fn test_cargo_toml_sqlx_postgres() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("sqlx = { version = \"0.8\", features = [\"runtime-tokio\", \"postgres\"] }"));
    }

    #[test]
    fn test_cargo_toml_tower_http() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("tower-http = { version = \"0.6\", features = [\"cors\", \"trace\"] }"));
    }

    #[test]
    fn test_cargo_toml_tracing() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("tracing = \"0.1\""));
        assert!(cargo.content.contains("tracing-subscriber = \"0.3\""));
    }

    #[test]
    fn test_cargo_toml_dotenvy() {
        let outputs = generate_project();
        let cargo = outputs.iter().find(|o| o.path == "Cargo.toml").unwrap();
        assert!(cargo.content.contains("dotenvy = \"0.15\""));
    }

    // ─── src/main.rs ────────────────────────────────────────────────────

    #[test]
    fn test_main_rs_path_and_overwrite() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.overwrite);
    }

    #[test]
    fn test_main_rs_tokio_main() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("#[tokio::main]"));
        assert!(main.content.contains("async fn main()"));
    }

    #[test]
    fn test_main_rs_dotenvy() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("dotenvy::dotenv().ok()"));
    }

    #[test]
    fn test_main_rs_database_url() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("DATABASE_URL"));
        assert!(main.content.contains("db::connect"));
    }

    #[test]
    fn test_main_rs_tracing_init() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("tracing_subscriber::fmt::init()"));
    }

    #[test]
    fn test_main_rs_router_creation() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("create_router()"));
        assert!(main.content.contains(".with_state(state)"));
    }

    #[test]
    fn test_main_rs_axum_serve() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("axum::serve(listener, app)"));
        assert!(main.content.contains(r#"std::env::var("PORT")"#));
        assert!(main.content.contains(r#""3000""#));
        assert!(main.content.contains(r#"format!("0.0.0.0:{}", port)"#));
    }

    #[test]
    fn test_main_rs_app_state() {
        let outputs = generate_project();
        let main = outputs.iter().find(|o| o.path == "src/main.rs").unwrap();
        assert!(main.content.contains("AppState { pool }"));
    }

    // ─── src/lib.rs ─────────────────────────────────────────────────────

    #[test]
    fn test_lib_rs_path_and_overwrite() {
        let outputs = generate_project();
        let lib = outputs.iter().find(|o| o.path == "src/lib.rs").unwrap();
        assert!(lib.overwrite);
    }

    #[test]
    fn test_lib_rs_path_attributes_for_typokit_modules() {
        let outputs = generate_project();
        let lib = outputs.iter().find(|o| o.path == "src/lib.rs").unwrap();
        assert!(lib.content.contains("#[path = \"../.typokit/models/mod.rs\"]"));
        assert!(lib.content.contains("pub mod models;"));
        assert!(lib.content.contains("#[path = \"../.typokit/router.rs\"]"));
        assert!(lib.content.contains("pub mod router;"));
        assert!(lib.content.contains("#[path = \"../.typokit/db/mod.rs\"]"));
        assert!(lib.content.contains("pub mod db;"));
        assert!(lib.content.contains("#[path = \"../.typokit/app.rs\"]"));
        assert!(lib.content.contains("pub mod app;"));
        assert!(lib.content.contains("#[path = \"../.typokit/error.rs\"]"));
        assert!(lib.content.contains("pub mod error;"));
    }

    #[test]
    fn test_lib_rs_user_code_modules() {
        let outputs = generate_project();
        let lib = outputs.iter().find(|o| o.path == "src/lib.rs").unwrap();
        assert!(lib.content.contains("pub mod handlers;"));
        assert!(lib.content.contains("pub mod services;"));
        assert!(lib.content.contains("pub mod middleware;"));
    }

    // ─── .typokit/app.rs ───────────────────────────────────────────────

    #[test]
    fn test_app_rs_path_and_overwrite() {
        let outputs = generate_project();
        let app = outputs.iter().find(|o| o.path == ".typokit/app.rs").unwrap();
        assert!(app.overwrite);
    }

    #[test]
    fn test_app_rs_derive_clone() {
        let outputs = generate_project();
        let app = outputs.iter().find(|o| o.path == ".typokit/app.rs").unwrap();
        assert!(app.content.contains("#[derive(Clone)]"));
    }

    #[test]
    fn test_app_rs_app_state_struct() {
        let outputs = generate_project();
        let app = outputs.iter().find(|o| o.path == ".typokit/app.rs").unwrap();
        assert!(app.content.contains("pub struct AppState"));
        assert!(app.content.contains("pub pool: PgPool"));
    }

    #[test]
    fn test_app_rs_imports() {
        let outputs = generate_project();
        let app = outputs.iter().find(|o| o.path == ".typokit/app.rs").unwrap();
        assert!(app.content.contains("use sqlx::postgres::PgPool;"));
    }

    // ─── .typokit/error.rs ─────────────────────────────────────────────

    #[test]
    fn test_error_rs_path_and_overwrite() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.overwrite);
    }

    #[test]
    fn test_error_rs_enum_variants() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("NotFound(String)"));
        assert!(err.content.contains("BadRequest(String)"));
        assert!(err.content.contains("Unauthorized(String)"));
        assert!(err.content.contains("Forbidden(String)"));
        assert!(err.content.contains("Conflict(String)"));
        assert!(err.content.contains("Internal(String)"));
    }

    #[test]
    fn test_error_rs_into_response_impl() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("impl IntoResponse for AppError"));
        assert!(err.content.contains("fn into_response(self) -> Response"));
    }

    #[test]
    fn test_error_rs_status_code_mapping() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("StatusCode::NOT_FOUND"));
        assert!(err.content.contains("StatusCode::BAD_REQUEST"));
        assert!(err.content.contains("StatusCode::UNAUTHORIZED"));
        assert!(err.content.contains("StatusCode::FORBIDDEN"));
        assert!(err.content.contains("StatusCode::CONFLICT"));
        assert!(err.content.contains("StatusCode::INTERNAL_SERVER_ERROR"));
    }

    #[test]
    fn test_error_rs_convenience_methods() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("pub fn not_found("));
        assert!(err.content.contains("pub fn bad_request("));
        assert!(err.content.contains("pub fn unauthorized("));
        assert!(err.content.contains("pub fn forbidden("));
        assert!(err.content.contains("pub fn conflict("));
        assert!(err.content.contains("pub fn internal("));
    }

    #[test]
    fn test_error_rs_imports() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("use axum::"));
        assert!(err.content.contains("StatusCode"));
        assert!(err.content.contains("IntoResponse"));
        assert!(err.content.contains("Json"));
        assert!(err.content.contains("use serde_json::json;"));
    }

    #[test]
    fn test_error_rs_display_impl() {
        let outputs = generate_project();
        let err = outputs.iter().find(|o| o.path == ".typokit/error.rs").unwrap();
        assert!(err.content.contains("impl std::fmt::Display for AppError"));
    }

    // ─── all files overwrite: true ──────────────────────────────────────

    #[test]
    fn test_all_outputs_overwrite_true() {
        let outputs = generate_project();
        for output in &outputs {
            assert!(
                output.overwrite,
                "Expected overwrite: true for {}, got false",
                output.path
            );
        }
    }

    // ─── deterministic output ───────────────────────────────────────────

    #[test]
    fn test_deterministic_output() {
        let outputs1 = generate_project();
        let outputs2 = generate_project();

        assert_eq!(outputs1.len(), outputs2.len());
        for (a, b) in outputs1.iter().zip(outputs2.iter()) {
            assert_eq!(a.path, b.path);
            assert_eq!(a.content, b.content);
            assert_eq!(a.overwrite, b.overwrite);
        }
    }

    // ─── auto-generated marker ──────────────────────────────────────────

    #[test]
    fn test_all_files_have_auto_generated_marker() {
        let outputs = generate_project();
        for output in &outputs {
            assert!(
                output.content.contains("AUTO-GENERATED by @typokit/transform-native"),
                "Missing auto-generated marker in {}",
                output.path
            );
        }
    }
}
