// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use server::app::AppState;
use server::db;
use server::router::create_router;

#[tokio::main]
async fn main() {
    dotenvy::dotenv().ok();

    tracing_subscriber::fmt::init();

    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");

    let pool = db::connect(&database_url).await;

    let state = AppState { pool };
    let app = create_router().with_state(state);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .expect("Failed to bind to 0.0.0.0:3000");

    tracing::info!("Server listening on 0.0.0.0:3000");

    axum::serve(listener, app)
        .await
        .expect("Server error");
}
