// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use sqlx::postgres::PgPool;

/// Shared application state passed to all route handlers.
#[derive(Clone)]
pub struct AppState {
    pub pool: PgPool,
}
