// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT

use axum::{
    Router,
    routing::get,
};
use crate::app::AppState;
use crate::handlers::todos;
use crate::handlers::users;

/// Create the application router with all route registrations.
pub fn create_router() -> Router<AppState> {
    Router::new()
        .route("/todos", get(todos::list).post(todos::create))
        .route(
            "/todos/{id}",
            get(todos::get_by_id)
                .put(todos::update)
                .delete(todos::delete),
        )
        .route("/users", get(users::list).post(users::create))
        .route(
            "/users/{id}",
            get(users::get_by_id)
                .put(users::update)
                .delete(users::delete),
        )
}
