// Migration: initial schema for users and todos tables (SQLite)
// Generated by: typokit migrate:generate --name initial

export const up = `
CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "display_name" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "todos" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "completed" INTEGER NOT NULL DEFAULT 0,
  "user_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);
`;

export const down = `
DROP TABLE IF EXISTS "todos";
DROP TABLE IF EXISTS "users";
`;
