/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Collect validator code results into a file path map.
 *
 * Maps type names to their output file paths under .typokit/validators/.
 */
export declare function collectValidatorOutputs(results: Array<Array<string>>): Record<string, string>

/**
 * Compile route contracts from TypeScript files into a radix tree.
 * Returns TypeScript source code for the compiled route table.
 */
export declare function compileRoutes(filePaths: Array<string>): string

/**
 * Diff two schema versions and produce a migration draft.
 *
 * Compares old_types against new_types to detect added/removed/modified
 * entities and fields. Generates SQL DDL stubs for the changes.
 */
export declare function diffSchemas(oldTypes: Record<string, JsTypeMetadata>, newTypes: Record<string, JsTypeMetadata>, migrationName: string): JsMigrationDraft

/**
 * Generate an OpenAPI 3.1.0 specification from route contracts and type definitions.
 * Returns the OpenAPI spec as a JSON string.
 */
export declare function generateOpenApi(routeFilePaths: Array<string>, typeFilePaths: Array<string>): string

/**
 * Generate contract test scaffolding from route contract files.
 *
 * Parses route contracts from the given files and generates TypeScript
 * test stubs with describe/it blocks for each route.
 */
export declare function generateTestStubs(filePaths: Array<string>): string

/** A migration draft (matches @typokit/types MigrationDraft) */
export interface JsMigrationDraft {
  name: string
  sql: string
  destructive: boolean
  changes: Array<JsSchemaChange>
}

/** Property metadata matching @typokit/types PropertyMetadata shape */
export interface JsPropertyMetadata {
  type: string
  optional: boolean
}

/** A single schema change (matches @typokit/types SchemaChange) */
export interface JsSchemaChange {
  type: string
  entity: string
  field?: string
  details?: Record<string, string>
}

/** Type metadata matching @typokit/types TypeMetadata shape */
export interface JsTypeMetadata {
  name: string
  properties: Record<string, JsPropertyMetadata>
}

/** Validator input for a single type (passed to Typia bridge callback) */
export interface JsTypeValidatorInput {
  name: string
  properties: Record<string, JsPropertyMetadata>
}

/**
 * Parse TypeScript source files and extract type metadata.
 *
 * Returns a SchemaTypeMap (Record<string, TypeMetadata>) mapping type names
 * to their extracted metadata including property types, optionality, and JSDoc tags.
 */
export declare function parseAndExtractTypes(filePaths: Array<string>): Record<string, JsTypeMetadata>

/**
 * Prepare type metadata for Typia validator generation.
 *
 * Converts parsed type metadata into a format suitable for passing
 * to the @typokit/transform-typia bridge callback.
 */
export declare function prepareValidatorInputs(typeFilePaths: Array<string>): Array<JsTypeValidatorInput>
