/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Property metadata matching @typokit/types PropertyMetadata shape */
export interface JsPropertyMetadata {
  type: string
  optional: boolean
}

/** Type metadata matching @typokit/types TypeMetadata shape */
export interface JsTypeMetadata {
  name: string
  properties: Record<string, JsPropertyMetadata>
}

/**
 * Parse TypeScript source files and extract type metadata.
 *
 * Returns a SchemaTypeMap (Record<string, TypeMetadata>) mapping type names
 * to their extracted metadata including property types, optionality, and JSDoc tags.
 */
export declare function parseAndExtractTypes(filePaths: Array<string>): Record<string, JsTypeMetadata>
