/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compile route contracts from TypeScript files into a radix tree.
 * Returns TypeScript source code for the compiled route table.
 */
export declare function compileRoutes(filePaths: Array<string>): string

/**
 * Generate an OpenAPI 3.1.0 specification from route contracts and type definitions.
 * Returns the OpenAPI spec as a JSON string.
 */
export declare function generateOpenApi(routeFilePaths: Array<string>, typeFilePaths: Array<string>): string

/** Property metadata matching @typokit/types PropertyMetadata shape */
export interface JsPropertyMetadata {
  type: string
  optional: boolean
}

/** Type metadata matching @typokit/types TypeMetadata shape */
export interface JsTypeMetadata {
  name: string
  properties: Record<string, JsPropertyMetadata>
}

/**
 * Parse TypeScript source files and extract type metadata.
 *
 * Returns a SchemaTypeMap (Record<string, TypeMetadata>) mapping type names
 * to their extracted metadata including property types, optionality, and JSDoc tags.
 */
export declare function parseAndExtractTypes(filePaths: Array<string>): Record<string, JsTypeMetadata>
