use crate::route_compiler::{RouteEntry, RouteTypeInfo, RouteObjectProp};

/// Generate contract test scaffolding from route entries.
///
/// Produces TypeScript test code using describe/it blocks that test:
/// - Valid request payloads return success
/// - Missing required fields return 400
/// - Invalid types return 400
pub fn generate_test_stubs(routes: &[RouteEntry]) -> String {
    let mut output = String::new();

    output.push_str("// AUTO-GENERATED by @typokit/transform-native — DO NOT EDIT\n");
    output.push_str("// Contract tests generated from route definitions\n");
    output.push_str("import { describe, it, expect } from \"@rstest/core\";\n");
    output.push_str("import { createTestClient } from \"@typokit/testing\";\n\n");
    output.push_str("const client = createTestClient();\n\n");

    for entry in routes {
        generate_route_test(&mut output, entry);
    }

    output
}

fn generate_route_test(output: &mut String, entry: &RouteEntry) {
    let label = format!("{} {}", entry.method, entry.path);
    output.push_str(&format!("describe(\"{}\", () => {{\n", label));

    // Test 1: Valid request
    generate_valid_request_test(output, entry);

    // Test 2: If body has required fields, test missing fields
    if has_required_fields(&entry.body_type) {
        generate_missing_fields_test(output, entry);
    }

    // Test 3: If params exist, test with valid params
    if !matches!(entry.params_type, RouteTypeInfo::Void) {
        generate_params_test(output, entry);
    }

    output.push_str("});\n\n");
}

fn generate_valid_request_test(output: &mut String, entry: &RouteEntry) {
    let method_lower = entry.method.to_lowercase();
    output.push_str("  it(\"accepts valid request\", async () => {\n");

    let path = convert_path_params(&entry.path);
    let has_body = !matches!(entry.body_type, RouteTypeInfo::Void);
    let has_query = !matches!(entry.query_type, RouteTypeInfo::Void);

    if has_body || has_query {
        output.push_str(&format!("    const res = await client.{}(\"{}\", {{\n", method_lower, path));
        if has_body {
            output.push_str("      body: ");
            output.push_str(&generate_sample_value(&entry.body_type, 3));
            output.push_str(",\n");
        }
        if has_query {
            output.push_str("      query: ");
            output.push_str(&generate_sample_value(&entry.query_type, 3));
            output.push_str(",\n");
        }
        output.push_str("    });\n");
    } else {
        output.push_str(&format!("    const res = await client.{}(\"{}\");\n", method_lower, path));
    }

    output.push_str("    expect(res.status).toBe(200);\n");
    output.push_str("  });\n\n");
}

fn generate_missing_fields_test(output: &mut String, entry: &RouteEntry) {
    let method_lower = entry.method.to_lowercase();
    let path = convert_path_params(&entry.path);

    output.push_str("  it(\"rejects missing required fields\", async () => {\n");
    output.push_str(&format!(
        "    const res = await client.{}(\"{}\", {{\n      body: {{}},\n    }});\n",
        method_lower, path
    ));
    output.push_str("    expect(res.status).toBe(400);\n");
    output.push_str("  });\n\n");
}

fn generate_params_test(output: &mut String, entry: &RouteEntry) {
    let method_lower = entry.method.to_lowercase();
    let path = convert_path_params(&entry.path);

    output.push_str("  it(\"handles path parameters\", async () => {\n");
    output.push_str(&format!(
        "    const res = await client.{}(\"{}\");\n",
        method_lower, path
    ));
    output.push_str("    expect(res.status).toBeDefined();\n");
    output.push_str("  });\n\n");
}

/// Convert route path params (`:id`) to sample values for test URLs
fn convert_path_params(path: &str) -> String {
    let mut result = String::new();
    for segment in path.split('/') {
        if segment.is_empty() {
            continue;
        }
        result.push('/');
        if segment.starts_with(':') {
            result.push_str("test-id");
        } else if segment.starts_with('*') {
            result.push_str("test/wildcard/path");
        } else {
            result.push_str(segment);
        }
    }
    if result.is_empty() {
        result.push('/');
    }
    result
}

/// Check if a type has required (non-optional) fields
fn has_required_fields(type_info: &RouteTypeInfo) -> bool {
    match type_info {
        RouteTypeInfo::ObjectLiteral(props) => props.iter().any(|p| !p.optional),
        RouteTypeInfo::Named(_) => true, // Assume named types have required fields
        _ => false,
    }
}

/// Generate a sample value string for a given type
fn generate_sample_value(type_info: &RouteTypeInfo, indent: usize) -> String {
    match type_info {
        RouteTypeInfo::Void => "undefined".to_string(),
        RouteTypeInfo::Primitive(p) => match p.as_str() {
            "string" => "\"test-value\"".to_string(),
            "number" => "42".to_string(),
            "boolean" => "true".to_string(),
            _ => "null".to_string(),
        },
        RouteTypeInfo::Named(name) => format!("{{}} as unknown as {}", name),
        RouteTypeInfo::ObjectLiteral(props) => {
            generate_object_sample(props, indent)
        }
        RouteTypeInfo::Array(inner) => {
            format!("[{}]", generate_sample_value(inner, indent))
        }
        RouteTypeInfo::StringLiteral(s) => format!("\"{}\"", s),
        RouteTypeInfo::NumberLiteral(n) => format!("{}", n),
        RouteTypeInfo::BooleanLiteral(b) => format!("{}", b),
        RouteTypeInfo::Union(variants) => {
            // Use first variant as sample
            if let Some(first) = variants.first() {
                generate_sample_value(first, indent)
            } else {
                "null".to_string()
            }
        }
        RouteTypeInfo::Generic(name, _args) => {
            format!("{{}} as unknown as {}", name)
        }
    }
}

fn generate_object_sample(props: &[RouteObjectProp], indent: usize) -> String {
    if props.is_empty() {
        return "{}".to_string();
    }

    let indent_str = "  ".repeat(indent);
    let inner_indent = "  ".repeat(indent + 1);
    let mut parts = Vec::new();

    for prop in props {
        if !prop.optional {
            parts.push(format!(
                "{}{}: {}",
                inner_indent,
                prop.name,
                generate_sample_value(&prop.type_info, indent + 1)
            ));
        }
    }

    if parts.is_empty() {
        "{}".to_string()
    } else {
        format!("{{\n{},\n{}}}", parts.join(",\n"), indent_str)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::route_compiler::{parse_path_segments, RouteEntry, RouteTypeInfo, RouteObjectProp};

    fn make_route(method: &str, path: &str, body: RouteTypeInfo) -> RouteEntry {
        RouteEntry {
            method: method.to_string(),
            path: path.to_string(),
            segments: parse_path_segments(path),
            handler_ref: format!("Test#{} {}", method, path),
            params_type: if path.contains(':') {
                RouteTypeInfo::ObjectLiteral(vec![RouteObjectProp {
                    name: "id".to_string(),
                    type_info: RouteTypeInfo::Primitive("string".into()),
                    optional: false,
                }])
            } else {
                RouteTypeInfo::Void
            },
            query_type: RouteTypeInfo::Void,
            body_type: body,
            response_type: RouteTypeInfo::Void,
        }
    }

    #[test]
    fn test_generate_stubs_basic() {
        let routes = vec![
            make_route("GET", "/users", RouteTypeInfo::Void),
        ];

        let output = generate_test_stubs(&routes);

        assert!(output.contains("AUTO-GENERATED"));
        assert!(output.contains("describe(\"GET /users\""));
        assert!(output.contains("accepts valid request"));
        assert!(output.contains("client.get(\"/users\")"));
    }

    #[test]
    fn test_generate_stubs_with_body() {
        let body = RouteTypeInfo::ObjectLiteral(vec![
            RouteObjectProp {
                name: "email".to_string(),
                type_info: RouteTypeInfo::Primitive("string".into()),
                optional: false,
            },
            RouteObjectProp {
                name: "name".to_string(),
                type_info: RouteTypeInfo::Primitive("string".into()),
                optional: false,
            },
        ]);
        let routes = vec![
            make_route("POST", "/users", body),
        ];

        let output = generate_test_stubs(&routes);

        assert!(output.contains("client.post(\"/users\""));
        assert!(output.contains("body:"));
        assert!(output.contains("email:"));
        assert!(output.contains("rejects missing required fields"));
        assert!(output.contains("body: {}"));
    }

    #[test]
    fn test_generate_stubs_with_params() {
        let routes = vec![
            make_route("GET", "/users/:id", RouteTypeInfo::Void),
        ];

        let output = generate_test_stubs(&routes);

        assert!(output.contains("GET /users/:id"));
        assert!(output.contains("test-id"));
        assert!(output.contains("handles path parameters"));
    }

    #[test]
    fn test_generate_stubs_multiple_routes() {
        let routes = vec![
            make_route("GET", "/users", RouteTypeInfo::Void),
            make_route("POST", "/users", RouteTypeInfo::ObjectLiteral(vec![
                RouteObjectProp {
                    name: "email".to_string(),
                    type_info: RouteTypeInfo::Primitive("string".into()),
                    optional: false,
                },
            ])),
            make_route("DELETE", "/users/:id", RouteTypeInfo::Void),
        ];

        let output = generate_test_stubs(&routes);

        assert!(output.contains("GET /users"));
        assert!(output.contains("POST /users"));
        assert!(output.contains("DELETE /users/:id"));
    }

    #[test]
    fn test_convert_path_params() {
        assert_eq!(convert_path_params("/users"), "/users");
        assert_eq!(convert_path_params("/users/:id"), "/users/test-id");
        assert_eq!(convert_path_params("/users/:userId/posts/:postId"), "/users/test-id/posts/test-id");
        assert_eq!(convert_path_params("/files/*path"), "/files/test/wildcard/path");
    }

    #[test]
    fn test_generate_sample_value_primitives() {
        assert_eq!(generate_sample_value(&RouteTypeInfo::Primitive("string".into()), 0), "\"test-value\"");
        assert_eq!(generate_sample_value(&RouteTypeInfo::Primitive("number".into()), 0), "42");
        assert_eq!(generate_sample_value(&RouteTypeInfo::Primitive("boolean".into()), 0), "true");
        assert_eq!(generate_sample_value(&RouteTypeInfo::Void, 0), "undefined");
    }

    #[test]
    fn test_generate_imports() {
        let routes = vec![make_route("GET", "/health", RouteTypeInfo::Void)];
        let output = generate_test_stubs(&routes);

        assert!(output.contains("import { describe, it, expect }"));
        assert!(output.contains("import { createTestClient }"));
        assert!(output.contains("const client = createTestClient()"));
    }
}
