// @typokit/cli — Generate Command Tests

import { describe, it, expect } from "@rstest/core";
import { createLogger } from "./index.js";
import type { GenerateCommandOptions, GenerateResult } from "./commands/generate.js";

// ─── executeGenerate dispatcher ─────────────────────────────

describe("executeGenerate", () => {
  it("returns error for unknown subcommand", async () => {
    const { executeGenerate } = await import("./commands/generate.js");
    const logger = createLogger({ verbose: false });

    const result = await executeGenerate({
      rootDir: "/nonexistent",
      config: {
        typeFiles: [],
        routeFiles: [],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger,
      subcommand: "nonexistent",
      flags: {},
      verbose: false,
    });

    expect(result.success).toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors[0]).toContain("Unknown generate subcommand");
  });

  it("dispatches to generate:db", async () => {
    const { executeGenerate } = await import("./commands/generate.js");
    const logger = createLogger({ verbose: false });

    const result = await executeGenerate({
      rootDir: "/nonexistent/empty",
      config: {
        typeFiles: [],
        routeFiles: [],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger,
      subcommand: "db",
      flags: {},
      verbose: false,
    });

    // With no type files, should succeed with no output
    expect(result.success).toBe(true);
    expect(result.filesWritten).toEqual([]);
  });

  it("dispatches to generate:client", async () => {
    const { executeGenerate } = await import("./commands/generate.js");
    const logger = createLogger({ verbose: false });

    const result = await executeGenerate({
      rootDir: "/nonexistent/empty",
      config: {
        typeFiles: [],
        routeFiles: [],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger,
      subcommand: "client",
      flags: {},
      verbose: false,
    });

    expect(result.success).toBe(true);
    expect(result.filesWritten).toEqual([]);
  });

  it("dispatches to generate:openapi", async () => {
    const { executeGenerate } = await import("./commands/generate.js");
    const logger = createLogger({ verbose: false });

    const result = await executeGenerate({
      rootDir: "/nonexistent/empty",
      config: {
        typeFiles: [],
        routeFiles: [],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger,
      subcommand: "openapi",
      flags: {},
      verbose: false,
    });

    expect(result.success).toBe(true);
    expect(result.filesWritten).toEqual([]);
  });

  it("dispatches to generate:tests", async () => {
    const { executeGenerate } = await import("./commands/generate.js");
    const logger = createLogger({ verbose: false });

    const result = await executeGenerate({
      rootDir: "/nonexistent/empty",
      config: {
        typeFiles: [],
        routeFiles: [],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger,
      subcommand: "tests",
      flags: {},
      verbose: false,
    });

    expect(result.success).toBe(true);
    expect(result.filesWritten).toEqual([]);
  });
});

// ─── generateClientCode ──────────────────────────────────────

describe("generateClientCode", () => {
  it("generates a valid TypeScript client module", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// compiled routes here");
    expect(code).toContain("export interface ClientOptions");
    expect(code).toContain("export interface RequestOptions");
    expect(code).toContain("export function createClient");
    expect(code).toContain("baseUrl");
  });

  it("includes auto-generated header comment", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// routes");
    expect(code).toContain("Auto-generated by @typokit/cli");
    expect(code).toContain("do not edit manually");
  });

  it("includes HTTP methods (get, post, put, patch, delete)", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// routes");
    expect(code).toContain('"GET"');
    expect(code).toContain('"POST"');
    expect(code).toContain('"PUT"');
    expect(code).toContain('"PATCH"');
    expect(code).toContain('"DELETE"');
  });

  it("includes query string serialization", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// routes");
    expect(code).toContain("encodeURIComponent");
  });

  it("includes param substitution", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// routes");
    expect(code).toContain("params");
    expect(code).toContain("replace");
  });

  it("includes compiled route reference", async () => {
    const { generateClientCode } = await import("./commands/generate.js");

    const code = generateClientCode("// my-compiled-routes");
    expect(code).toContain("my-compiled-routes");
  });
});

// ─── GenerateResult interface shape ──────────────────────────

describe("GenerateResult", () => {
  it("has expected shape", () => {
    const result: GenerateResult = {
      success: true,
      filesWritten: ["/some/path/file.ts"],
      duration: 42,
      errors: [],
    };
    expect(result.success).toBe(true);
    expect(result.filesWritten.length).toBe(1);
    expect(result.duration).toBe(42);
    expect(result.errors.length).toBe(0);
  });

  it("works with errors", () => {
    const result: GenerateResult = {
      success: false,
      filesWritten: [],
      duration: 10,
      errors: ["Something went wrong"],
    };
    expect(result.success).toBe(false);
    expect(result.errors[0]).toBe("Something went wrong");
  });
});

// ─── GenerateCommandOptions interface shape ──────────────────

describe("GenerateCommandOptions", () => {
  it("accepts all required fields", () => {
    const opts: GenerateCommandOptions = {
      rootDir: "/my/project",
      config: {
        typeFiles: ["src/**/*.types.ts"],
        routeFiles: ["src/**/*.routes.ts"],
        outputDir: ".typokit",
        distDir: "dist",
        compiler: "tsc",
        compilerArgs: [],
      },
      logger: createLogger({ verbose: false }),
      subcommand: "openapi",
      flags: { output: "./dist/openapi.json" },
      verbose: false,
    };
    expect(opts.subcommand).toBe("openapi");
    expect(opts.flags["output"]).toBe("./dist/openapi.json");
  });
});

// ─── CLI integration: parseArgs for generate commands ────────

describe("parseArgs with generate commands", () => {
  it("parses generate:openapi command", async () => {
    const { parseArgs } = await import("./index.js");
    const result = parseArgs(["node", "typokit", "generate:openapi", "--output", "./dist/api.json"]);
    expect(result.command).toBe("generate:openapi");
    expect(result.flags["output"]).toBe("./dist/api.json");
  });

  it("parses generate:db command", async () => {
    const { parseArgs } = await import("./index.js");
    const result = parseArgs(["node", "typokit", "generate:db", "--verbose"]);
    expect(result.command).toBe("generate:db");
    expect(result.flags["verbose"]).toBe(true);
  });

  it("parses generate:client command", async () => {
    const { parseArgs } = await import("./index.js");
    const result = parseArgs(["node", "typokit", "generate:client"]);
    expect(result.command).toBe("generate:client");
  });

  it("parses generate:tests command", async () => {
    const { parseArgs } = await import("./index.js");
    const result = parseArgs(["node", "typokit", "generate:tests", "--root", "/my/project"]);
    expect(result.command).toBe("generate:tests");
    expect(result.flags["root"]).toBe("/my/project");
  });
});

// ─── resolveFilePatterns ─────────────────────────────────────

describe("resolveGenerateFilePatterns", () => {
  it("returns empty array for nonexistent dir patterns", async () => {
    const { resolveGenerateFilePatterns } = await import("./commands/generate.js");
    const files = await resolveGenerateFilePatterns("/nonexistent/dir", ["src/**/*.ts"]);
    expect(files).toEqual([]);
  });

  it("returns empty for empty patterns", async () => {
    const { resolveGenerateFilePatterns } = await import("./commands/generate.js");
    const files = await resolveGenerateFilePatterns("/nonexistent", []);
    expect(files).toEqual([]);
  });
});
